### ISSUE TITLE
Coolapk推出了问答模式

### ISSUE THREAD

**Issue by Kostamn** [bggRGjQaUbCoE/c001apk#25]
![Screenshot_2024-03-01-15-18-50-749_com example c001apk-edit](https://github.com/bggRGjQaUbCoE/c001apk/assets/104090388/239fd742-3585-40b1-8160-7f167b70b363)
coolapk推出了新的类似知乎的问答模式 目前无法回复

**Comment by bggRGjQaUbCoE** [comment]
别回复
