### ISSUE TITLE
发布动态和评论提示系统环境异常

### ISSUE THREAD

**Issue by GalaxySaturn** [bggRGjQaUbCoE/c001apk#47]
![Screenshot_20240323_122536_com example c001apk](https://github.com/bggRGjQaUbCoE/c001apk/assets/78467111/3d8a5fcf-bd6f-443e-bcf5-cc966cd78d69)
发布动态和评论的时候提示系统环境异常，更换网络之后没用，但是没有办法更换系统，这个怎么解决

**Comment by SamSuu** [comment]
fixed？

**Comment by bayosolin** [comment]
解决了吗？

**Comment by bggRGjQaUbCoE** [comment]
> 解决了吗？

这是问题吗？
