### ISSUE TITLE
添加选项（不使用MD3样式底栏）

### ISSUE THREAD

**Issue by PengJiX** [bggRGjQaUbCoE/c001apk#48]
可以多一种底栏显示风格吗？目前在用安卓11的系统，看起来和其他APP对比很有违和感😞
例如像第三方B站pilipala这样
![Screenshot_20240327_151417](https://github.com/bggRGjQaUbCoE/c001apk/assets/127209201/35e7819c-6cbd-4d9d-86ec-8f5a2d24af8e)
![Screenshot_20240327_151357](https://github.com/bggRGjQaUbCoE/c001apk/assets/127209201/1910cb8c-2b7d-405e-a5d5-b11888428352)

**Comment by bggRGjQaUbCoE** [comment]
不加
