### ISSUE TITLE
双击放大图片

### ISSUE THREAD

**Issue by 2584191127** [bggRGjQaUbCoE/c001apk#52]
希望能添加这个功能

**Comment by bggRGjQaUbCoE** [comment]
有啊

**Comment by 2584191127** [comment]
> 有啊

发现要查看原图才行
能不能不查看原图的时候也能放大？长图也是查看原图后才能往下拉

**Comment by bggRGjQaUbCoE** [comment]
> > 有啊
> 
> 发现要查看原图才行 能不能不查看原图的时候也能放大？长图也是查看原图后才能往下拉

第一个，去https://github.com/mikaelzero/mojito反馈
第二个，长图非原图是裁剪过的，你怎么下拉
