### ISSUE TITLE
备注功能

### ISSUE THREAD

**Issue by WoAiNianChu** [bggRGjQaUbCoE/c001apk#53]
哥，**新版本酷安加了备注功能**，自我觉得这个功能挺实用的，考虑跟进不
![536381_bfa71fd3_8166_2403_870@1080x2160.jpeg](https://github.com/bggRGjQaUbCoE/c001apk/assets/112552691/94a2be50-2fcf-4a29-8d6b-f1825209d8a9)

**Comment by bggRGjQaUbCoE** [comment]
没啥用
