### ISSUE TITLE
平板上竖屏时应用页面的fab边距异常

### ISSUE THREAD

**Issue by onlymash** [bggRGjQaUbCoE/c001apk#55]
如图，fab与底栏重叠。
版本: 1a7af44(357)

![markup_1000018538](https://github.com/bggRGjQaUbCoE/c001apk/assets/5838634/b8d6cca9-3518-418b-8b68-799e0b151f88)

**Comment by bggRGjQaUbCoE** [comment]
什么系统，看起来没获取到你的导航栏高度

**Comment by fiepi** [comment]
> 什么系统，看起来没获取到你的导航栏高度

拯救者Y700+PixelOS(GSI)。
应该不是系统的原因，你在AS创建一个平板设备的模拟器试一下

**Comment by fiepi** [comment]
> 什么系统，看起来没获取到你的导航栏高度

简单看了一下代码，你的写法不对，不要直接尝试去获取导航栏的高度，因为系统边距是动态会变化的，而你这样直接获取的值是固定的。比如分屏时就露馅了，如图分屏后fab的底部边距就太大了。

![Screenshot_2024-03-31-12-24-47-82_e25e263aec300c4b3438606d06608afa](https://github.com/bggRGjQaUbCoE/c001apk/assets/15153999/c3690248-5664-4363-946d-808413591017)

正确写法大概是这样

```
ViewCompat.setOnApplyWindowInsetsListener(view) { view, insets ->
    val systemBars= windowInsets.getInsets(WindowInsetsCompat.Type.systemBars())
    fab.updateLayoutParams<MarginLayoutParams>(bottomMargin = systemBars.bottom  )
    insets
}

```

**Comment by fiepi** [comment]
同样的道理，写死后横屏时也会引发类似的边距异常。
![IMG_20240331_124347](https://github.com/bggRGjQaUbCoE/c001apk/assets/15153999/9481df86-6c03-426e-ac06-67a8bf7b4b97)
所以还是得用ViewCompat.setOnApplyWindowInsetsListener这个方法，一次性能得到上下左右四个方向的系统栏大小

**Comment by bggRGjQaUbCoE** [comment]
> > 什么系统，看起来没获取到你的导航栏高度
> 
> 简单看了一下代码，你的写法不对，不要直接尝试去获取导航栏的高度，因为系统边距是动态会变化的，而你这样直接获取的值是固定的。比如分屏时就露馅了，如图分屏后fab的底部边距就太大了。
> 
> ![Screenshot_2024-03-31-12-24-47-82_e25e263aec300c4b3438606d06608afa](https://private-user-images.githubusercontent.com/15153999/318241634-c3690248-5664-4363-946d-808413591017.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjEwNzIsIm5iZiI6MTcxMTg2MDc3MiwicGF0aCI6Ii8xNTE1Mzk5OS8zMTgyNDE2MzQtYzM2OTAyNDgtNTY2NC00MzYzLTk0NmQtODA4NDEzNTkxMDE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA0NTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwODZlYTliOTQ1YmNhMzFhNmMwZjkyYzg1MWU0MTUyMWI1M2I0MzY3MThlYTFhMTRkOGQzNDlmYjkxNzk4Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2e1Lnmv7DC2Lzvj-e8RSXeAgEkfNWdWrZzZdvK-zjAg)
> 
> 正确写法大概是这样
> 
> ```
> ViewCompat.setOnApplyWindowInsetsListener(view) { view, insets ->
>     val systemBars= insets.getInsets(WindowInsetsCompat.Type.systemBars())
>     fab.updateLayoutParams<MarginLayoutParams>(bottomMargin = systemBars.bottom  )
>     insets
> }
> ```

OK，感谢
