### ISSUE TITLE
点击“查看更多”无反应

### ISSUE THREAD

**Issue by Ktyf37** [bggRGjQaUbCoE/c001apk#6]
![Screenshot_20240211_013902_com example c001apk](https://github.com/bggRGjQaUbCoE/c001apk/assets/135925971/511cf806-de42-4d5a-86b8-fd06dad65ce6)

**Comment by bggRGjQaUbCoE** [comment]
正常

**Comment by bggRGjQaUbCoE** [comment]
fixed
