### ISSUE TITLE
账号登录不上，一直提示图像验证码错误

### ISSUE THREAD

**Issue by ranyu2005918** [bggRGjQaUbCoE/c001apk#71]

**Comment by bggRGjQaUbCoE** [comment]
修了https://github.com/bggRGjQaUbCoE/c001apk/commit/a624bc4b771ac644d474917c5dc4b8ff888f6466

**Comment by ranyu2005918** [comment]
没有啊![Screenshot_20240510_102828.jpg](https://github.com/bggRGjQaUbCoE/c001apk/assets/168494538/7c2004cb-d9ee-42f0-ac54-f3e1a3af0cca)

**Comment by bggRGjQaUbCoE** [comment]
版本号？

**Comment by ranyu2005918** [comment]
36300ae

**Comment by bggRGjQaUbCoE** [comment]
> 36300ae

？
